In [178]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.metrics import confusion_matrix   ## these 3 confusion, f1_score, accuracy is to test how good is our model
from sklearn.metrics import f1_score

This example is taken from simplilearn tutorial videos 

It is about loan payment system for bank, based on the our model bank can decide whether it should approve loan request from the costumers or not.

They are not using 5th columns for their model so I am also not doing, it is removed by them in their tutorial video.




In [179]:
balance_data = pd.read_csv('Decision_Tree_ Dataset.csv',sep= ',', header= 0)

In [180]:
print ("Dataset Length:: ", len(balance_data))
print ("Dataset Shape:: ", balance_data.shape)

Dataset Length::  1000
Dataset Shape::  (1000, 6)


In [181]:
print ("Dataset:: ")
balance_data.head()

# result here means returned loan or not of past data

Dataset:: 


Initilal payment   Last payment   credit score   house number   total sum  \
0               201          10018            250           3046       13515   
1               205          10016            395           3044       13660   
2               257          10129            109           3251       13746   
3               246          10064            324           3137       13771   
4               117          10115            496           3094       13822   

   Result  
0     yes  
1     yes  
2     yes  
3     yes  
4     yes

In [186]:
X = balance_data.values[:, :4]
#print(X)
Y = balance_data.values[:, 5]

In [187]:
#print(balance_data)

In [183]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.2, random_state = 100)

In [168]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth=3, min_samples_leaf=5)
clf_entropy.fit(X_train, y_train)


DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

1. max_depth = maximum depth of the tree, 3 means the nodes are expanded to 3 decision nodes. It helps to lower the risk of over fitting or makes less complex tree
2.min_samples_leaf means the minimum no.of samples required to be at a leaf node. A split point at any depth will only be considered if it leaves at least min_samples_leaf training samples.

In [169]:
print(type(X_test))
print(X_test)

<class 'numpy.ndarray'>
[[104 12125 700 3138]
 [351 11140 965 4127]
 [204 13439 191 3720]
 [276 12290 478 3923]
 [326 13167 381 3826]
 [237 11197 580 3340]
 [287 12863 678 3516]
 [457 11931 932 4292]
 [101 14811 877 4410]
 [316 14790 333 4236]
 [258 14371 126 3265]
 [251 14100 530 3838]
 [245 11833 202 3212]
 [106 13372 265 4466]
 [440 13941 492 3575]
 [247 12000 328 4245]
 [286 10713 819 4671]
 [325 14201 279 4721]
 [498 11421 407 4116]
 [177 13540 236 4047]
 [369 14601 666 4270]
 [438 10317 947 4171]
 [498 14355 163 4616]
 [180 10806 388 3224]
 [370 11302 365 3251]
 [429 14404 162 3050]
 [153 14016 866 4210]
 [166 10100 233 4123]
 [423 12682 406 4180]
 [103 14895 496 3255]
 [250 14996 621 3964]
 [157 10372 801 4320]
 [480 11743 508 3012]
 [185 11072 502 4436]
 [481 12517 403 3017]
 [183 14528 356 3435]
 [214 13255 796 4338]
 [445 12726 827 4411]
 [428 11654 167 3321]
 [196 12258 350 4362]
 [366 10762 773 3688]
 [276 11978 106 3187]
 [165 11017 439 4268]
 [440 13094 113 3688]
 [430 13

In [170]:
y_pred_en = clf_entropy.predict(X_test)
print(y_pred_en)

['yes' 'yes' 'No' 'yes' 'No' 'yes' 'yes' 'No' 'No' 'No' 'No' 'No' 'yes'
 'No' 'No' 'No' 'yes' 'No' 'yes' 'No' 'No' 'yes' 'No' 'yes' 'yes' 'No'
 'No' 'yes' 'No' 'No' 'No' 'yes' 'yes' 'yes' 'yes' 'No' 'No' 'No' 'yes'
 'No' 'yes' 'yes' 'yes' 'yes' 'No' 'yes' 'No' 'yes' 'No' 'No' 'yes' 'No'
 'yes' 'yes' 'yes' 'yes' 'No' 'yes' 'No' 'yes' 'yes' 'No' 'No' 'yes' 'No'
 'yes' 'yes' 'yes' 'No' 'yes' 'No' 'No' 'No' 'yes' 'No' 'yes' 'yes' 'No'
 'yes' 'No' 'No' 'No' 'No' 'yes' 'No' 'yes' 'No' 'yes' 'yes' 'No' 'yes'
 'yes' 'yes' 'yes' 'yes' 'No' 'yes' 'yes' 'yes' 'yes' 'No' 'No' 'yes'
 'yes' 'No' 'yes' 'yes' 'yes' 'No' 'No' 'yes' 'yes' 'yes' 'No' 'No' 'yes'
 'yes' 'yes' 'No' 'No' 'No' 'No' 'yes' 'yes' 'No' 'yes' 'yes' 'yes' 'No'
 'No' 'yes' 'yes' 'No' 'yes' 'yes' 'yes' 'No' 'yes' 'yes' 'No' 'No' 'yes'
 'yes' 'yes' 'No' 'yes' 'yes' 'yes' 'yes' 'No' 'yes' 'No' 'No' 'No' 'No'
 'yes' 'No' 'yes' 'No' 'yes' 'yes' 'No' 'yes' 'yes' 'No' 'yes' 'No' 'yes'
 'No' 'No' 'No' 'yes' 'No' 'yes' 'No' 'yes' 'yes' 'No' 

In [171]:
print ("Accuracy is {} % " .format(accuracy_score(y_test,y_pred_en)*100))

## Based on this accuracy score the bank can decide whether it can approve the loan request from the customer or not.

Accuracy is 93.0 % 


In [172]:
## just trying my self to test with individual person 

## say a person has initial payment 250,  last payment 10000, credit score 500 & house number 3456
## then I can predict whether person will pay loan or not in the following way

mm = np.array([250, 10000, 500, 3456])
print(mm.reshape((1,-1)))

y_pred_ex = clf_entropy.predict(mm.reshape((1,-1)))
print(y_pred_ex)

## write random function with seed and check yes or no 

[[  250 10000   500  3456]]
['yes']


In [173]:
mm = np.array([199, 13775, 150, 4765])
print(mm.reshape((1,-1)))

y_pred_ex = clf_entropy.predict(mm.reshape((1,-1)))
print(y_pred_ex)

[[  199 13775   150  4765]]
['No']


In [174]:
print(len(y_test))
print(len(y_test[y_test == 'yes']))
print(len(y_test[y_test == 'No']))

200
102
98


In [175]:
print(len(y_pred_en))
print(len(y_pred_en[y_pred_en == 'yes']))
print(len(y_pred_en[y_pred_en == 'No']))

200
106
94


In [176]:
cm = confusion_matrix(y_test, y_pred_en)
print (cm)

[[89  9]
 [ 5 97]]


The F1 score can be interpreted as a harmonic mean of the precision and recall, where an F1 score reaches its best value at 1 and worst score at 0. The relative contribution of precision and recall to the F1 score are equal. The formula for the F1 score is:

F1 = 2 * (precision * recall) / (precision + recall)

In [167]:
print(f1_score(y_test, y_pred_en, pos_label = 'yes'))  # precision score only for "yes" label
print(f1_score(y_test, y_pred_en, pos_label = 'No'))  # precision score only for "No" label

0.9377990430622011
0.9319371727748691
